# "on" for activate the teleportation on connection
# "off" for deactivate the teleportation on connection
status: "on"

teleport_coordinates:
  world: world
  x: 0.0
  y: 90
  z: 0.0
  yaw: 0.0
  pitch: 0.0

messages:
  no_permission: "&eYatsuuTeleport&f >&4 You do not have {permission} to run this command."
  teleport_point: "&eYatsuuTeleport&f >&a Teleport location and direction set !"
  not_player_send_command: "&eYatsuuTeleport&f >&c This command can only be executed by a player."
  player_not_found: "&eYatsuuTeleport&f >&c Player not found."
  usage_teleport: "&eYatsuuTeleport&f >&4 /teleport [Player]"
  sender_teleport: "&eYatsuuTeleport&f >&a {player} has been teleported to the server spawn."
  target_teleport: "&eYatsuuTeleport&f >&a You've been teleported to the server spawn."
  success_reload: "&eYatsuuTeleport&f >&a Configuration reloaded."
  commands: "&eYatsuuTeleport&f >&a Available commands :"
  command_format: "&e/{command} : &f{description}"
